version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: ruby calculation_spec.rb
